---
apiVersion: v1
kind: Secret
metadata:
  name: operator-oauth
  namespace: tailscale
data:
  client_id: "{{ .Values.secrets.tailscale.client_id | b64enc }}"
  client_secret: "{{ .Values.secrets.tailscale.client_secret | b64enc }}"
