---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tld
  namespace: cert-manager
spec:
  secretName: tld-tls
  issuerRef:
    name: "{{ .Values.secrets.global.letsencrypt_issuer }}"
    kind: ClusterIssuer
  dnsNames:
    - "*.vault.{{ .Values.secrets.global.tld }}"
    - "*.{{ .Values.secrets.global.tld }}"
    - "{{ .Values.secrets.global.tld }}"
