---
ingress-nginx:
  controller:
    image:
      runAsUser: 10001
    kind: DaemonSet
    config:
      custom-http-errors: 400,401,403,404,500,502,503,504
      global-auth-method: GET
      global-auth-url: http://authelia.auth.svc.cluster.local/api/verify
      global-auth-response-headers: Remote-User,Remote-Name,Remote-Groups,Remote-Email
      global-auth-cache-key: "$remote_user$http_cookie"
      global-auth-cache-duration: "200 202 30m, 401 1m"
      global-auth-snippet: |
        proxy_set_header X-Forwarded-Method $request_method;
      force-ssl-redirect: "true"
      proxy-body-size: "0"
      ssl-protocols: "TLSv1.3 TLSv1.2"
      ssl-redirect: "false"
    extraArgs:
      default-ssl-certificate: cert-manager/tld-tls
    extraEnvs:
      - name: TZ
        value: Europe/Warsaw
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        additionalLabels:
          release: prometheus-stack
    containerSecurityContext:
      allowPrivilegeEscalation: false
    #resources:
      #requests:
        #memory: 512Mi
      #limits:
        #memory: 1024Mi
    admissionWebhooks:
      createSecretJob:
        securityContext:
          allowPrivilegeEscalation: false
        #resources:
          #requests:
            #memory: 512Mi
          #limits:
            #memory: 1024Mi
      patchWebhookJob:
        securityContext:
          allowPrivilegeEscalation: false
        #resources:
          #requests:
            #memory: 512Mi
          #limits:
            #memory: 1024Mi
  defaultBackend:
    enabled: true
    replicaCount: 2
    image:
      repository: ghcr.io/tarampampam/error-pages
      tag: 2.20.0
    extraEnvs:
      - name: TEMPLATE_NAME
        value: app-down
      - name: SHOW_DETAILS
        value: "false"
    #resources:
      #requests:
        #memory: 512Mi
      #limits:
        #memory: 1024Mi
