---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: trusted-pool
  namespace: metallb-system
spec:
  addresses:
    - 10.100.40.10-10.100.40.250
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: untrusted-pool
  namespace: metallb-system
spec:
  addresses:
    - 10.200.40.10-10.200.40.250
