---
# yaml-language-server: $schema=https://json.schemastore.org/chart.json
apiVersion: v2
name: mail-relay
version: 1.0.0
type: application
dependencies:
  - name: mail
    version: v3.6.1
    repository: https://bokysan.github.io/docker-postfix/
