---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: mail-relay
  namespace: mail-relay
stringData:
  # yamllint disable rule:line-length
  _enable_sasl2.sh: |-
    #!/usr/bin/env bash
    set -e

    mkdir -p /etc/sasl2 || true
    echo -n '{{ .Values.secrets.mail_relay.ingress.password }}' | saslpasswd2 -c -p -f /etc/sasl2/sasldb2 -u {{ .Values.secrets.mail_relay.ingress.domain }} {{ .Values.secrets.mail_relay.ingress.username }}
    chmod 755 /etc/sasl2
    chmod 644 /etc/sasl2/* || true
  # yamllint enable
  relayhost-password: "{{ .Values.secrets.mail_relay.egress.password }}"
  smtpd.conf: |-
    pwcheck_method: auxprop
    auxprop_plugin: sasldb
    mech_list: PLAIN LOGIN
